module.exports = {
    BACKCOLOR: '#202020',
    TEXTCOLOR: '#FFFFFF',
    PRIMARYCOLOR: '#383838',
    SECONDARYCOLOR: '#2ECC71',
    ACTIVECOLOR: 'white',
    INACTIVECOLOR: 'gray',
    BORDERCOLOR: '#161616',
    SHADOWCOLOR: 'black'
};